---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Process OS Specific Setup
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'