---

# upstart is required for the Xenial version of mongodb.
- name: Install Upstart
  apt:
    name: upstart
    state: installed
  when: ansible_distribution = 'xenial'
- name: Install Upstart SYSV
  apt:
    name: upstart-sysv
    state: installed
  when: ansible_distribution = 'xenial'

# Add repository key for MongoDB
- name: Add repository key
  apt_key:
    id: EA312927
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xEA312927"
    state: present

- name: Add mongodb apt source
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}/mongodb-org/3.2 {{ __mongodb_repository_section }}"
    state: present
    filename: mongodb-org-3.2

- name: Install MongoDb Server
  apt:
    name: mongodb-org-server
    state: installed