---

# Add repository key for MongoDB
- name: Add repository key
  apt_key:
    id: EA312927
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xEA312927"
    state: present

- name: Add mongodb apt source
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}/mongodb-org/3.2 {{ __mongodb_repository_section }}"
    state: present
    filename: mongodb-org-3.2

- name: Install MongoDb Server
  apt:
    name: mongodb-org-server
    state: installed

- name: copy mongod template for Xenial
  template:
    src: "mongod.service.{{ ansible_distribution_release }}.j2"
    dest: "/etc/systemd/system/mongod.service"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == 'xenial'
